version: '3.8'

services:
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - ./pgsql/.env
    volumes:
      - pgsql-volume:/var/lib/postgresql/data
    networks:
      - cursdb


networks:
  cursdb:
    driver: bridge

volumes:
  pgsql-volume:
    driver: local

